Vagrant.configure("2") do |c|
  c.vm.box = "learningchef/centos65"
  c.vm.box_url = "learningchef/centos65"
  c.vm.hostname = "node-centos65.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.33.35"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/pbomars/chef-repo", "/chef-repo", nil
  c.vm.provider :virtualbox do |p|
  end
end
