Vagrant.configure("2") do |c|
  c.vm.box = "learningchef/centos65"
  c.vm.box_url = "learningchef/centos65"
  c.vm.hostname = "server-centos65.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.33.34"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "1536"]
  end
end
